language: python

python: 3.5
env:
    - TOXENV=py27
    - TOXENV=py33
    - TOXENV=py34
    - TOXENV=py35
    - TOXENV=pep8
    - TOXENV=coverage
install:
    - pip install tox
    - if [ "$TOXENV" = 'coverage' ]; then pip install coveralls; fi
script:
    - tox -e $TOXENV
after_success:
    - if [ "$TOXENV" = 'coverage' ]; then coveralls; fi
deploy:
    provider: pypi
    user: seantis
    password:
        secure: i+DqFD2GtsosNTuK1ryfVIXm+Ysani9zm66YeaOD8O0788+9kuWqTMJbSAgNF8fwrUW2Qn2ZXTNF/UU9SC+L93upbog1rhDmfcdkV9Tybn7hzeJzA7LXvNgGFN4p/KT3P4IbAfGzIV2N8KRZ7qmSqWCdUvlYLde9JriU3efy9Jg=
    distributions: "sdist bdist_wheel"
    on:
        tags: true
        condition: $TOXENV = py35
